### PR TITLE
Adding missing semi-colon fixes CI build.

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Review by facchinm — CHANGES_REQUESTED** [review]
I'd rather try to get rid of `setSpiMode` and replace with proper and portable `SPISettings` . WDYT? :slightly_smiling_face:

**Comment by aentinger** [comment]
> I'd rather try to get rid of `setSpiMode` and replace with proper and portable `SPISettings` . WDYT? slightly_smiling_face

Because this library is for a SAMD-only board. Otherwise I'd agree with you.

**Comment by aentinger** [comment]
> I'd rather try to get rid of `setSpiMode` and replace with proper and portable `SPISettings` . WDYT? slightly_smiling_face

Done, see 174f07138b5f02df3d615434ba80236d2210d5f6 :wink:

**Comment by aentinger** [comment]
Adafruit caused CI errors are currently being fixed, see https://github.com/arduino/ArduinoCore-samd/issues/654 . Therefore merging. CI errors should be resolved once Adafruit releases working versions for `Adafruit_BusIO`. FYI @ladyada (I can see from your latest commits to Adafruit_BusIO::master that you are in fact working on it :wink:).

**Pull request merged**
